apiVersion: v2
title: Jupyter Notebook as Editor for Eclipse Che
displayName: Jupyter Notebook
description: Jupyter Notebook as Editor for Eclipse Che
icon: https://jupyter.org/assets/main-logo.svg
repository: https://github.com/ws-skeleton/che-editor-jupyter/
firstPublicationDate: "2019-02-05"
endpoints:
  - name: "jupyter"
    public: true
    targetPort: 8888
    attributes:
      protocol: http
      type: ide
containers:
  - name: jupyter-notebook
    image: "docker.io/ksmster/che-editor-jupyter:5.7.0"
    env:
      - name: JUPYTER_NOTEBOOK_DIR
        value: /projects
    mountSources: true
    ports:
     - exposedPort: 8888
    memoryLimit: "512M"
